version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '8080:80'
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - '3333:3333'
    depends_on:
      - postgresql
    links:
      - postgresql
    networks:
      - backend
    command: sh -c "node ace migration:run && node bin/server.js"

  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/letsencrypt
    ports:
      - '80:80'
      # - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
