version: '3.8'

services:
  client-app:
    image: bean2509/nftmarketplace-client
    env_file:
      - ./frontend/.env
    expose:
      - '5000'

  backend-app:
    image: bean2509/nftmarketplace-backend
    env_file:
      - .env
    expose:
      - '3333'
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node ace migration:fresh && node ace db:seed && node bin/server.js"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: market
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost --silent']
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client-app
      - backend-app

volumes:
  mysql-data:
