version: '3'

services:
  server:
    build: .
    expose:
      - ${PORT}
    env_file:
      - .env
    depends_on:
      - postgresql
    command: sh -c "node ace migration:run && node bin/server.js"

  postgresql:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - ${POST}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
    depends_on:
      - server
    command: /bin/sh -c "envsubst '$$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - PORT=${PORT}

volumes:
  pgdata:
